### ISSUE TITLE
docker镜像的版本不是qBittorrent-Enhanced-Edition

### ISSUE THREAD

**Issue by hyy-666** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#1]
Docker-qBittorrent-Enhanced-Edition的作者您好，您的docker镜像的qBittorrent不是Enhanced-Edition，麻烦您排查一下。

**Comment by SuperNG6** [comment]
可能是其他项目写错标签了？我重新编译推送了一下，大概两个小时后会好
