### ISSUE TITLE
大佬，请问可以编译个4.2.5.10版本的？

### ISSUE THREAD

**Issue by ftrildz** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#13]
4.3.0以上版本，一下载文件几分钟后就会崩溃，进程CPU直接飙至100%，谢谢大佬了，麻烦了！！

**Comment by SuperNG6** [comment]
新版从之前自编译，更换为`c0re100 `本人编译的版本
哪天有空我再编译一个老版本吧

**Comment by 4488dsq** [comment]
同求

**Comment by SuperNG6** [comment]
先构建了一个x86_64版本的镜像，arm版的编译脚本我得再改改，过几天再出。
docker pull superng6/qbittorrentee:4.2.5.16

**Comment by ftrildz** [comment]
> 先构建了一个x86_64版本的镜像，arm版的编译脚本我得再改改，过几天再出。
> docker pull superng6/qbittorrentee:4.2.5.16

谢谢大佬!感谢🙏
