### ISSUE TITLE
配置种子监控文件夹无效

### ISSUE THREAD

**Issue by zhaoawd** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#14]
在选项里配置监控文件夹保存后再打开为空，请问具体的参数项是什么，我想直接设置docker的变量来解决这个问题

**Comment by SuperNG6** [comment]
把监控文件夹放在`/downloads/内`

**Comment by zhaoawd** [comment]
> 把监控文件夹放在`/downloads/内`

我想明白了，我用的docker，但是没有把同步种子的路径给映射到docker内部，实际配置的是docker内部地址，低级错误，哎。
