### ISSUE TITLE
运行容器时报错：s6-mkdir: warning: unable to mkdir /var: Directory not empty

### ISSUE THREAD

**Issue by TigerDen96** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#2]
如题所示，运行后容器自动退出，查看日志返回如下信息：
`s6-mkdir: warning: unable to mkdir /var: Directory not empty`
请问该如何解决呢？

**Comment by TigerDen96** [comment]
与此同时，我发现您提供的文档存在如下错误：
[<img src = 'https://ftp.bmp.ovh/imgs/2020/04/199e1a228726c654.png' />](url)
1. 忘记加   \
2. qbittorrentee:latest 写成了 qbittorrent:latest

可以顺便修正一下

**Comment by SuperNG6** [comment]
1、这个问题很奇怪，你挂载了 /var 目录？这个是基础镜像自带的脚本，我所修改的部分在这部分的上层，理论来说和我这边没有关系
2、感谢提醒，已更正

**Comment by TigerDen96** [comment]
我试着部署了qBittorrent官方的镜像，仍然出现同样的问题。看来不是这里的问题，我自己再想想办法吧。最后感谢您的耐心回复~
