### ISSUE TITLE
缺少IPv6地址用户的做种，有什么解决方法吗？

### ISSUE THREAD

**Issue by zzz6839** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#21]
近来发现docker版本的和PC桌面端版本的qbittorrent相比缺少IPv6用户的连接，同时也少了很多的DHT，进而影响了下载速度，网上没有找到解决方法，特此来问一下。

**Comment by SuperNG6** [comment]
容器选择host网络模式，路由器开启ipv6即可
如果你的本身没有ipv6地址，那么无法连接ipv6用户

**Comment by zzz6839** [comment]
解决了，谢谢大佬

**Comment by huxuan** [comment]
> 解决了，谢谢大佬

可以分享一下是如何解决的吗？谢谢大佬~

**Comment by SuperNG6** [comment]
> > 解决了，谢谢大佬
> 
> 可以分享一下是如何解决的吗？谢谢大佬~
创建容器的时候网络选择host模式
![Zgs9vs](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2023-08-01/Zgs9vs.png)

**Comment by ZZZ-zero** [comment]
请教个问题，我在fnos里已经将网络修改为host模式，以下为docker-compose：
`version: "2"
services:
  qbittorrentee:
    image: superng6/qbittorrentee
    container_name: qbittorrentee
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - WEB_USER=admin
      - WEB_PASSWORD=veryscrect
    volumes:
      - /path/to/appdata/config:/config
      - /vol1/1000/qb/downloads:/downloads
    network_mode: host
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped`
但是启动容器后，网络状态中ipv6仍然显示禁用状态，有没有什么好办法
![image](https://github.com/user-attachments/assets/e528fc9f-d414-4405-920f-1212a1945902)

![image](https://github.com/user-attachments/assets/9dab2e49-090b-4cac-9a87-c594d0469c05)

注，fnos已正常获取ipv6：
![image](https://github.com/user-attachments/assets/2f2d4ea6-e60b-4e93-b218-418021e36920)
