### ISSUE TITLE
docker tag设为`latest`时拉取的不是最新版本

### ISSUE THREAD

**Issue by Rocky-CN** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#29]
docker地址为 https://hub.docker.com/r/superng6/qbittorrentee

如下图所示：
![image](https://user-images.githubusercontent.com/56460701/160228638-3a2a3e12-6c43-4624-a6c3-9d43ed3dcb4e.png)

docker命令为 `docker pull superng6/qbittorrentee`
拉取到的镜像信息为
```shell
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
superng6/qbittorrentee   latest              2f8eba272905        4 months ago        91.4MB
```
#### 总结：
`latest`标签拉取到的是4个月前的版本。

**Comment by abcfy2** [comment]
你用的镜像站没有同步吧？建议使用上海交大的，他们家是反向代理，其他家都是定期同步的：https://mirrors.sjtug.sjtu.edu.cn/docs/docker-registry
