### ISSUE TITLE
上游wei-ui出bug了

### ISSUE THREAD

**Issue by dycwuxing** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#39]
https://github.com/qbittorrent/qBittorrent/issues/18618
请参考~

**Comment by SuperNG6** [comment]
看到了，已更新v4.5.2.10

另外，不是对最新版有非常强烈的需求，强别建议使用v4.3.9，我自己也是一只在用这个版本，最稳定，资源占用也少

**Comment by dycwuxing** [comment]
好的，谢谢😀
