### ISSUE TITLE
无法登录,- WebAPI 登录失败。原因：凭证无效

### ISSUE THREAD

**Issue by Tigerest** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#48]
貌似也是qbit本身的问题，找了网上的方案解决似乎也没有用。。。。。

**Comment by calvinchai** [comment]
好像是因为前几天的版本更新，建议docker pull前一个版本的镜像

**Comment by yumo509** [comment]
我也遇到这个web登录失败问题

**Comment by yumo509** [comment]
目前能用默认密码登录的版本是4.6.0.10

**Comment by Tigerest** [comment]
我现在一个比较抽象的解决办法是在qBittorrent.conf中加上这一行
`WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"`
然后就能强制用admin adminadmin登录了，登上webUI之后在webUI里改用户名密码就没问题。
虽然我也不知道为什么可行，但是确实可行。（

**Comment by calvinchai** [comment]
> 我现在一个比较抽象的解决办法是在qBittorrent.conf中加上这一行 `WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"` 然后就能强制用admin adminadmin登录了，登上webUI之后在webUI里改用户名密码就没问题。 虽然我也不知道为什么可行，但是确实可行。（

这个大概就是adminadmin这个密码的hash 相当于你手动设置了这个密码

**Comment by 1Googol** [comment]
#46 可以查看这个issue
