### ISSUE TITLE
作者你好 我是萌新 想问下8080端口可以改成别的吗 怎么修改配置文件

### ISSUE THREAD

**Issue by gcphym** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#6]

**Comment by SuperNG6** [comment]
这样修改
https://github.com/SuperNG6/docker-qbittorrent/issues/3

**Comment by gcphym** [comment]
> 这样修改
> [SuperNG6/docker-qbittorrent#3](https://github.com/SuperNG6/docker-qbittorrent/issues/3)

会了 十分感谢
